[package]
name = "actix-blog"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
mini_markdown = "0.3"
