version: '3.8'
x-aws-vpc: vpc-16bb5172
services:
  app:
    build:
      context: .
    image: drujensen/actix-blog:latest
    platform: linux/arm64
    command: /app/actix-blog
    environment:
      - ACTIX_ADDRESS=0.0.0.0
      - ACTIX_PORT=80
    ports:
      - 80:80
